// Package calendarsync syncs Google Calendar events into an org file
// (:sync-calendar — see internal/ui) by wrapping internal/gcal (a thin,
// org-agnostic API client) with the org-file rendering and orchestration
// gcalsync used to own as a separate binary.
package calendarsync

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/sburnett/orgtd/internal/gcal"
	"github.com/sburnett/orgtd/internal/org"
)

// maxMeetingDuration is the longest an event may run and still be
// synced — see ExcludeTooLong. Applies uniformly, all-day events
// included: an all-day event is, by construction (see eventBounds),
// always at least 24 hours and so is always excluded by this rule —
// there's no "all-day but under 6 hours" case to preserve.
const maxMeetingDuration = 6 * time.Hour

// ExcludeTooLong drops any event running longer than maxMeetingDuration.
// A handful of misconfigured or overly-broad calendar entries (an
// entire-day block someone forgot to mark as a real all-day event, a
// botched recurring series) otherwise clutter the synced file and,
// worse, look "in progress" for hours on end in the "gM" picker (see
// internal/ui/agenda.go's meetingCandidates). Returns a new slice;
// events is left untouched.
func ExcludeTooLong(events []gcal.Event) []gcal.Event {
	kept := make([]gcal.Event, 0, len(events))
	for _, ev := range events {
		start, end := eventBounds(ev)
		if end.Sub(start) > maxMeetingDuration {
			continue
		}
		kept = append(kept, ev)
	}
	return kept
}

// BuildFile renders events into a fresh org.File at path: one top-level,
// keyword-less headline per event instance (they're calendar entries,
// not actionable tasks), each carrying a plain (non-SCHEDULED) timestamp
// in its body — so the file is browsable in the outline but doesn't
// contribute to orgtd's own agenda computation. The whole file is meant
// to be wholesale-regenerated on every sync (it's a cache, not something
// hand-edited), so nothing here reads or preserves a previous version.
// attendeeTagDomains restricts each headline's attendee tags to
// attendees whose email ends in one of those domains, and
// attendeeIgnorePatterns drops any attendee whose email matches one of
// those glob patterns before tags are even considered (see
// attendeeTags) — empty means no restriction/no exclusions.
func BuildFile(path string, events []gcal.Event, attendeeTagDomains, attendeeIgnorePatterns []string) *org.File {
	sorted := make([]gcal.Event, len(events))
	copy(sorted, events)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].Start.Before(sorted[j].Start)
	})

	f := &org.File{
		Path: path,
		Preamble: []string{
			"# -*- mode: org; buffer-read-only: t -*-",
			"# Generated by :sync-calendar — do not edit by hand, your changes will",
			"# be overwritten on the next sync.",
			"",
		},
	}
	for _, ev := range sorted {
		f.Headlines = append(f.Headlines, buildHeadline(ev, attendeeTagDomains, attendeeIgnorePatterns))
	}
	return f
}

func buildHeadline(ev gcal.Event, attendeeTagDomains, attendeeIgnorePatterns []string) *org.Headline {
	title := ev.Summary
	if title == "" {
		title = "(no title)"
	}

	h := &org.Headline{
		Level: 1,
		Title: title,
	}
	if ev.RecurringEventID != "" {
		// Visible at a glance in the outline, without having to open
		// the property drawer, that this instance is part of a series.
		h.Tags = append(h.Tags, "recurring")
	}
	h.Tags = append(h.Tags, attendeeTags(ev, attendeeTagDomains, attendeeIgnorePatterns)...)
	h.SetProperty("GCAL_EVENT_ID", ev.ID)
	h.SetProperty("GCAL_CALENDAR_ID", ev.CalendarID)
	// Read back by internal/ui's "gM" picker (meetingCandidate.accepted)
	// to require acceptance, not just invitation, before a meeting counts
	// as "in progress" for ranking purposes — see meetingPickerLess.
	h.SetProperty("GCAL_SELF_RESPONSE_STATUS", ev.SelfResponseStatus)
	if ev.RecurringEventID != "" {
		// Stable across every occurrence of the series (unlike
		// GCAL_EVENT_ID above, which is this one instance's own ID) —
		// what a task or project would associate with, per DESIGN.md's
		// project<->meeting concept, to mean "this recurring meeting" in
		// general rather than one specific occurrence of it.
		h.SetProperty("GCAL_RECURRING_EVENT_ID", ev.RecurringEventID)
	}
	start, end := eventBounds(ev)
	h.SetProperty("GCAL_START", start.Format(time.RFC3339))
	h.SetProperty("GCAL_END", end.Format(time.RFC3339))
	if ev.HTMLLink != "" {
		// Machine-readable copy of the link below, so orgtd can resolve
		// a GCAL_EVENT_IDS reference on some other entry back to this
		// event's URL (and this title) without having to parse it back
		// out of body text — see the status line's "current entry's
		// link" feature in internal/ui.
		h.SetProperty("GCAL_HTML_LINK", ev.HTMLLink)
	}

	indent := strings.Repeat(" ", h.Level+1)
	h.Body = append(h.Body, indent+orgTimestamp(ev))

	if ev.Location != "" {
		h.Body = append(h.Body, indent+"Location: "+ev.Location)
	}
	if ev.Description != "" {
		h.Body = append(h.Body, "")
		for _, line := range strings.Split(strings.TrimRight(ev.Description, "\n"), "\n") {
			h.Body = append(h.Body, indent+line)
		}
	}
	if ev.HTMLLink != "" {
		h.Body = append(h.Body, "", indent+"[["+ev.HTMLLink+"][Open in Google Calendar]]")
	}

	return h
}

// maxAttendeesForTags caps how large an event can be and still get
// attendee tags (see attendeeTags) — a large all-hands or broadcast
// invite would otherwise bury the handful of tags that are actually
// useful (a small meeting's own participants) under dozens of others.
// Declined attendees never count toward this cap (see attendeeTags) —
// they're not attending, so a big invite list that mostly declined is
// still a small, meaningful meeting as far as the cap is concerned.
const maxAttendeesForTags = 7

// attendeeTags returns one "@username" tag per attendee tagged on ev,
// derived from the portion of their email address before the "@" — e.g.
// "john@example.com" becomes "@john". Confirmed attendees (Google's
// "accepted" response status) are prioritized: when the invite (minus
// anyone who's declined) is small enough on its own — at most
// maxAttendeesForTags people — RSVP status doesn't matter and everyone
// still pending or tentative is tagged too, since a meeting that small is
// meaningful regardless of who's formally confirmed yet. Once the invite
// grows past that, only confirmed attendees are considered, and if even
// those exceed maxAttendeesForTags, tagging is skipped entirely (no tags
// at all, rather than a partial list) — a large invite list with just a
// few confirmed attendees is exactly the small, meaningful meeting the
// cap is meant to let through. Either way, an attendee with no email or
// whose address has nothing before the "@" is skipped. If domains is
// non-empty, an attendee is tagged only when their address's domain
// (case-insensitive, a leading "@" in a configured domain ignored)
// exactly matches one of them — see domainAllowed; an empty domains list
// (the default) tags every eligible attendee regardless of domain.
// Before any of that, an attendee whose email matches one of
// ignorePatterns (see attendeeIgnored) is dropped outright — e.g.
// "c_*@*" to exclude the synthetic "c_...@..." attendees Google Calendar
// attaches to represent a resource/room booking.
func attendeeTags(ev gcal.Event, domains, ignorePatterns []string) []string {
	var invited []gcal.Attendee
	for _, a := range ev.Attendees {
		if a.ResponseStatus != "declined" {
			invited = append(invited, a)
		}
	}

	candidates := invited
	if len(invited) > maxAttendeesForTags {
		candidates = nil
		for _, a := range invited {
			if a.ResponseStatus == "accepted" {
				candidates = append(candidates, a)
			}
		}
		if len(candidates) > maxAttendeesForTags {
			return nil
		}
	}

	var tags []string
	for _, a := range candidates {
		if attendeeIgnored(a.Email, ignorePatterns) {
			continue
		}
		username, domain, ok := splitEmail(a.Email)
		if !ok || !domainAllowed(domain, domains) {
			continue
		}
		tags = append(tags, "@"+sanitizeTag(username))
	}
	sort.Strings(tags)
	return tags
}

// attendeeIgnored reports whether email matches one of patterns (see
// Settings.AttendeeIgnorePatterns), each a filepath.Match-style glob —
// "*" matches any run of characters, "?" a single one — compared
// case-insensitively against the whole address. False (nothing ignored)
// when patterns is empty; a malformed pattern is treated as "does not
// match" rather than failing the whole sync.
func attendeeIgnored(email string, patterns []string) bool {
	email = strings.ToLower(email)
	for _, p := range patterns {
		if matched, err := filepath.Match(strings.ToLower(p), email); err == nil && matched {
			return true
		}
	}
	return false
}

// splitEmail splits email into the portion before and after its "@", or
// ok = false if email has nothing before it to extract (no "@", or
// nothing before it — domain, after the "@", may legitimately be empty
// and still ok).
func splitEmail(email string) (username, domain string, ok bool) {
	at := strings.IndexByte(email, '@')
	if at <= 0 {
		return "", "", false
	}
	return email[:at], email[at+1:], true
}

// domainAllowed reports whether domain passes the AttendeeTagDomains
// restriction (see Settings.AttendeeTagDomains): true unconditionally
// when domains is empty (no restriction configured), otherwise true only
// if domain case-insensitively matches one of domains — each compared
// with any leading "@" stripped first, so "example.com" and
// "@example.com" behave the same in the config file.
func domainAllowed(domain string, domains []string) bool {
	if len(domains) == 0 {
		return true
	}
	for _, d := range domains {
		if strings.EqualFold(strings.TrimPrefix(d, "@"), domain) {
			return true
		}
	}
	return false
}

// sanitizeTag replaces any character s that org's own tag syntax
// doesn't allow (see tagsRe in internal/org — letters, digits, and
// "_@%#+" only) with "_", so an email's local part — which routinely
// has "."s, and sometimes "-"s, neither valid in an org tag — still
// round-trips through calendar.org as a real tag rather than silently
// failing to parse back out as one on the next load.
func sanitizeTag(s string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		case r == '_' || r == '@' || r == '%' || r == '#' || r == '+':
			return r
		}
		return '_'
	}, s)
}

// orgTimestamp formats ev's start/end as a single org timestamp (a plain
// one, not a SCHEDULED/DEADLINE planning line — see BuildFile), using a
// "start--end" range only when the event actually spans more than one
// calendar day.
func orgTimestamp(ev gcal.Event) string {
	if ev.AllDay {
		// Google's all-day End date is exclusive (a 1-day event has
		// End = Start + 1 day), so the last inclusive day is End minus
		// one day.
		lastDay := ev.End.AddDate(0, 0, -1)
		if !lastDay.After(ev.Start) {
			return "<" + ev.Start.Format("2006-01-02 Mon") + ">"
		}
		return "<" + ev.Start.Format("2006-01-02 Mon") + ">--<" + lastDay.Format("2006-01-02 Mon") + ">"
	}

	start := ev.Start.Local()
	end := ev.End.Local()
	if sameDay(start, end) {
		return fmt.Sprintf("<%s %s-%s>", start.Format("2006-01-02 Mon"), start.Format("15:04"), end.Format("15:04"))
	}
	return fmt.Sprintf("<%s %s>--<%s %s>",
		start.Format("2006-01-02 Mon"), start.Format("15:04"),
		end.Format("2006-01-02 Mon"), end.Format("15:04"))
}

// eventBounds returns ev's start/end as absolute instants suitable for
// an "is now within this event" check (see orgtd's own capture code,
// which reads these back out of GCAL_START/GCAL_END properties). Timed
// events already carry a correct absolute instant from the API. An
// all-day event's Start/End are bare calendar dates with no meaningful
// timezone of their own (see parseEventTime in internal/gcal), so
// they're anchored to local midnight here — the same "local" the rest
// of orgtd uses, since this runs in the same process.
func eventBounds(ev gcal.Event) (start, end time.Time) {
	if !ev.AllDay {
		return ev.Start, ev.End
	}
	local := func(t time.Time) time.Time {
		y, m, d := t.Date()
		return time.Date(y, m, d, 0, 0, 0, 0, time.Local)
	}
	return local(ev.Start), local(ev.End)
}

func sameDay(a, b time.Time) bool {
	ay, am, ad := a.Date()
	by, bm, bd := b.Date()
	return ay == by && am == bm && ad == bd
}
