package main

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/sburnett/orgtd/internal/gcal"
	"github.com/sburnett/orgtd/internal/org"
)

// maxMeetingDuration is the longest a *timed* event may run and still be
// synced — see ExcludeTooLong. All-day events are exempt: they're not
// meetings in the usual sense (a holiday, an out-of-office block, a
// full-day placeholder), and every single one of them would trivially
// exceed this just by being all-day.
const maxMeetingDuration = 6 * time.Hour

// ExcludeTooLong drops any timed event running longer than
// maxMeetingDuration, leaving every all-day event untouched regardless
// of its span. A handful of misconfigured or overly-broad calendar
// entries (an entire-day "meeting" block someone forgot to mark
// all-day, a botched recurring series) otherwise clutter the synced
// file and, worse, look "in progress" for hours on end in the "gM"
// picker (see internal/ui/agenda.go's meetingCandidates). Returns a new
// slice; events is left untouched.
func ExcludeTooLong(events []gcal.Event) []gcal.Event {
	kept := make([]gcal.Event, 0, len(events))
	for _, ev := range events {
		if !ev.AllDay {
			start, end := eventBounds(ev)
			if end.Sub(start) > maxMeetingDuration {
				continue
			}
		}
		kept = append(kept, ev)
	}
	return kept
}

// BuildFile renders events into a fresh org.File at path: one top-level,
// keyword-less headline per event instance (they're calendar entries,
// not actionable tasks), each carrying a plain (non-SCHEDULED) timestamp
// in its body — so the file is browsable in the outline but doesn't
// contribute to orgtd's own agenda computation. The whole file is meant
// to be wholesale-regenerated on every sync (it's a cache, not something
// hand-edited), so nothing here reads or preserves a previous version.
func BuildFile(path string, events []gcal.Event) *org.File {
	sorted := make([]gcal.Event, len(events))
	copy(sorted, events)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].Start.Before(sorted[j].Start)
	})

	f := &org.File{
		Path: path,
		Preamble: []string{
			"# -*- mode: org; buffer-read-only: t -*-",
			"# Generated by gcalsync — do not edit by hand, your changes will be",
			"# overwritten on the next sync.",
			"",
		},
	}
	for _, ev := range sorted {
		f.Headlines = append(f.Headlines, buildHeadline(ev))
	}
	return f
}

func buildHeadline(ev gcal.Event) *org.Headline {
	title := ev.Summary
	if title == "" {
		title = "(no title)"
	}

	h := &org.Headline{
		Level: 1,
		Title: title,
	}
	if ev.RecurringEventID != "" {
		// Visible at a glance in the outline, without having to open
		// the property drawer, that this instance is part of a series.
		h.Tags = []string{"recurring"}
	}
	h.SetProperty("GCAL_EVENT_ID", ev.ID)
	h.SetProperty("GCAL_CALENDAR_ID", ev.CalendarID)
	if ev.RecurringEventID != "" {
		// Stable across every occurrence of the series (unlike
		// GCAL_EVENT_ID above, which is this one instance's own ID) —
		// what a task or project would associate with, per DESIGN.md's
		// project<->meeting concept, to mean "this recurring meeting" in
		// general rather than one specific occurrence of it.
		h.SetProperty("GCAL_RECURRING_EVENT_ID", ev.RecurringEventID)
	}
	start, end := eventBounds(ev)
	h.SetProperty("GCAL_START", start.Format(time.RFC3339))
	h.SetProperty("GCAL_END", end.Format(time.RFC3339))
	if ev.HTMLLink != "" {
		// Machine-readable copy of the link below, so orgtd can resolve
		// a GCAL_EVENT_IDS reference on some other entry back to this
		// event's URL (and this title) without having to parse it back
		// out of body text — see the status line's "current entry's
		// link" feature in internal/ui.
		h.SetProperty("GCAL_HTML_LINK", ev.HTMLLink)
	}

	indent := strings.Repeat(" ", h.Level+1)
	h.Body = append(h.Body, indent+orgTimestamp(ev))

	if ev.Location != "" {
		h.Body = append(h.Body, indent+"Location: "+ev.Location)
	}
	if ev.Description != "" {
		h.Body = append(h.Body, "")
		for _, line := range strings.Split(strings.TrimRight(ev.Description, "\n"), "\n") {
			h.Body = append(h.Body, indent+line)
		}
	}
	if ev.HTMLLink != "" {
		h.Body = append(h.Body, "", indent+"[["+ev.HTMLLink+"][Open in Google Calendar]]")
	}

	return h
}

// orgTimestamp formats ev's start/end as a single org timestamp (a plain
// one, not a SCHEDULED/DEADLINE planning line — see BuildFile), using a
// "start--end" range only when the event actually spans more than one
// calendar day.
func orgTimestamp(ev gcal.Event) string {
	if ev.AllDay {
		// Google's all-day End date is exclusive (a 1-day event has
		// End = Start + 1 day), so the last inclusive day is End minus
		// one day.
		lastDay := ev.End.AddDate(0, 0, -1)
		if !lastDay.After(ev.Start) {
			return "<" + ev.Start.Format("2006-01-02 Mon") + ">"
		}
		return "<" + ev.Start.Format("2006-01-02 Mon") + ">--<" + lastDay.Format("2006-01-02 Mon") + ">"
	}

	start := ev.Start.Local()
	end := ev.End.Local()
	if sameDay(start, end) {
		return fmt.Sprintf("<%s %s-%s>", start.Format("2006-01-02 Mon"), start.Format("15:04"), end.Format("15:04"))
	}
	return fmt.Sprintf("<%s %s>--<%s %s>",
		start.Format("2006-01-02 Mon"), start.Format("15:04"),
		end.Format("2006-01-02 Mon"), end.Format("15:04"))
}

// eventBounds returns ev's start/end as absolute instants suitable for
// an "is now within this event" check (see orgtd's own capture code,
// which reads these back out of GCAL_START/GCAL_END properties). Timed
// events already carry a correct absolute instant from the API. An
// all-day event's Start/End are bare calendar dates with no meaningful
// timezone of their own (see parseEventTime in internal/gcal), so they're
// anchored to local midnight here — gcalsync and orgtd run on the same
// machine, so "local" agrees between the two.
func eventBounds(ev gcal.Event) (start, end time.Time) {
	if !ev.AllDay {
		return ev.Start, ev.End
	}
	local := func(t time.Time) time.Time {
		y, m, d := t.Date()
		return time.Date(y, m, d, 0, 0, 0, 0, time.Local)
	}
	return local(ev.Start), local(ev.End)
}

func sameDay(a, b time.Time) bool {
	ay, am, ad := a.Date()
	by, bm, bd := b.Date()
	return ay == by && am == bm && ad == bd
}
