// meeting_tags.go implements durable, per-meeting tags recorded in a
// dedicated file (see WithMeetingTagsFile) rather than on calendar.org's
// own headlines, since those are wholesale-regenerated by every
// :sync-calendar run (see internal/calendarsync). "gt" on a calendarView
// entry (see applyTagInput in tag_prompt.go) routes here instead of editing
// the entry directly; meetingTags (agenda.go) and
// renderCalendarItemRowWithBg (render_rows.go) both read the result back live,
// so nothing needs to be "baked into" calendar.org for either the
// tag-based-linking machinery or the calendar view's own display to stay
// correct across a resync.
package ui

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/sburnett/orgtd/internal/meetings"
	"github.com/sburnett/orgtd/internal/org"
)

// calendarDisplayTags returns the tags renderCalendarItemRowWithBg
// should show on a calendar event's own row: h's own tags (recurring,
// attendee) followed by any meeting-tags.org tags for it that aren't
// already present — purely a rendering-time union (see meetings.Index.TagRecord
// above), so it never mutates h.Tags itself. h is assumed to be a synced
// calendar event; a no-op union (just h.Tags) if it somehow isn't.
func (m *Model) calendarDisplayTags(h *org.Headline) []string {
	key, ok := meetings.Identity(h)
	if !ok {
		return h.Tags
	}
	record := m.meetingIndex().TagRecord(key.Kind, key.ID)
	if record == nil || len(record.Tags) == 0 {
		return h.Tags
	}
	tags := append([]string(nil), h.Tags...)
	for _, t := range record.Tags {
		if indexOfString(tags, t) < 0 {
			tags = append(tags, t)
		}
	}
	return tags
}

// indexOfHeadline returns the index of h within list, or -1 if it isn't
// there — used by applyMeetingTag to locate an existing meeting-tags.org
// entry's position for a deleteAction, the same way callers elsewhere in
// this package locate a headline's index before building a spliceAction.
func indexOfHeadline(list []*org.Headline, h *org.Headline) int {
	for i, cand := range list {
		if cand == h {
			return i
		}
	}
	return -1
}

// applyMeetingTag is "gt" on a calendarView entry (see applyTagInput):
// rather than editing the calendar event's own headline, which
// :sync-calendar would wipe out on its next wholesale regeneration, it
// records tag durably in meeting-tags.org instead — toggling it on
// whichever entry already records tags for this meeting (kind/id — see
// meetings.Identity), or creating a new one, seeded with target's own
// title for context, if none exists yet. Every branch below is exactly
// one pushUndo call touching only meeting-tags.org, so this is a single
// undo step, same as any other "gt" edit — calendar.org's live headline
// is never touched.
func (m *Model) applyMeetingTag(target *org.Headline, kind meetings.Kind, id, tag string) {
	if tag == meetings.SeriesTag {
		m.message = `"recurring" is reserved and can't be used as a meeting tag`
		return
	}

	tagsFile := m.findMeetingTagsFile()
	if tagsFile == nil {
		// Nothing has ever been tagged via "gt" before — materialize the
		// file's workspace entry lazily, mirroring exactly how
		// finishSyncCalendar (sync_calendar.go) does the same for the
		// calendar file the first time :sync-calendar runs.
		tagsFile = &org.File{Path: filepath.Join(m.ws.Dir, m.meetingTagsFile)}
		m.ws.Files = append(m.ws.Files, tagsFile)
		sort.Slice(m.ws.Files, func(i, j int) bool { return m.ws.Files[i].Path < m.ws.Files[j].Path })
	}

	existing := m.meetingIndex().TagRecord(kind, id)
	if existing == nil {
		h := &org.Headline{Level: 1, Title: target.Title, Tags: []string{tag}}
		h.SetProperty(kind.TagsIDsProperty(), id)
		m.pushUndo(&insertAction{spliceAction{f: tagsFile, index: len(tagsFile.Headlines), headlines: []*org.Headline{h}}})
		return
	}

	old := append([]string(nil), existing.Tags...)
	var newTags []string
	removed := false
	for _, t := range existing.Tags {
		if t == tag {
			removed = true
			continue
		}
		newTags = append(newTags, t)
	}
	if !removed {
		newTags = append(newTags, tag)
	}
	if removed && len(newTags) == 0 {
		// The last tag on this entry was just removed — nothing left to
		// record, so prune the whole headline rather than leaving a
		// meaningless tagless stub behind.
		parent := existing.Parent
		list := tagsFile.Headlines
		if parent != nil {
			list = parent.Children
		}
		index := indexOfHeadline(list, existing)
		m.pushUndo(&deleteAction{spliceAction{f: tagsFile, parent: parent, index: index, headlines: []*org.Headline{existing}, inTree: true}})
		return
	}
	m.pushUndo(&tagChangeAction{h: existing, f: tagsFile, oldTags: old, newTags: newTags})
}

// meetingTagEvents returns every currently-synced calendar event
// occurrence (across the whole workspace, any file) that the
// meeting-tags.org record h names — nil if h isn't a record at all, or
// none of its IDs currently resolve to a synced occurrence. That second
// case is meeting-tags.org's own window into a stale record: an ID whose
// series was deleted and recreated (a new GCAL_RECURRING_EVENT_ID), or a
// one-off event that's aged out of the sync window, simply shows nothing
// nested under it in meetingTagsView, rather than silently doing nothing
// forever. Sorted chronologically by start time, like :calendar's own
// day-by-day ordering.
func (m *Model) meetingTagEvents(h *org.Headline) []*org.Headline {
	return m.meetingIndex().EventsFor(
		strings.Fields(h.Properties[meetings.Recurring.TagsIDsProperty()]),
		strings.Fields(h.Properties[meetings.OneOff.TagsIDsProperty()]))
}

// appendMeetingTagsHeadlines is appendHeadlines' meetingTagsView
// counterpart (see appendMeetingTagsRows, rows.go): same recursion
// (body lines, children), but a headline that's itself a
// meeting-tags.org record (meetings.IsTagRecord) is marked
// isMeetingTagsRecordRow (see renderMeetingTagsRecordRowWithBg — a
// tighter row than the default headline case, no indent/fold columns),
// and has every calendar event it currently matches
// (meetingTagEvents) appended right after it, one level
// deeper — the meeting-tags.org analogue of appendCalendarHeadlines
// nesting linked items under each event, so browsing :meeting-tags shows
// at a glance which synced occurrences a record's IDs actually resolve
// to right now. Genuinely one level deeper (not flush with the record),
// and not just visually: row.level is also what moveDeeper/
// moveShallower (see nav.go) use to decide what "l"/"h" step into or
// out of, so a nested event's level is what makes it reachable as the
// record's "child" via those keys, the same way
// renderCalendarLinkedItemRowWithBg's r.level-based indent does for
// :calendar's own linked items (its actual rendered indent is separately
// capped — see renderCalendarItemRowWithBg). Each nested event row is
// marked isCalendarItem, the same as its own row in :calendar (same
// headline pointer), so it renders, folds, and edits identically —
// including "gt", which applyTagInput routes right back to this same
// record.
func (m *Model) appendMeetingTagsHeadlines(dst *[]row, headlines []*org.Headline, ignoreFold bool) {
	for _, h := range headlines {
		if m.hiddenAsStaleDone(h) {
			continue
		}
		*dst = append(*dst, row{headline: h, level: h.Level, isMeetingTagsRecordRow: meetings.IsTagRecord(h)})
		if ignoreFold || !m.collapsed[h] {
			m.appendBodyLines(dst, h)
			if len(h.Children) > 0 {
				m.appendMeetingTagsHeadlines(dst, h.Children, ignoreFold)
			}
		}
		for _, event := range m.meetingTagEvents(h) {
			if _, ok := m.collapsed[event]; !ok {
				m.collapsed[event] = true
			}
			*dst = append(*dst, row{headline: event, level: h.Level + 1, isCalendarItem: true})
			if ignoreFold || !m.collapsed[event] {
				m.appendBodyLines(dst, event)
			}
		}
	}
}
