// meeting_tags.go implements durable, per-meeting tags recorded in a
// dedicated file (see WithMeetingTagsFile) rather than on calendar.org's
// own headlines, since those are wholesale-regenerated by every
// :sync-calendar run (see internal/calendarsync). "gt" on a calendarView
// entry (see applyTagInput in model.go) routes here instead of editing
// the entry directly; meetingTags (agenda.go) and
// renderCalendarItemRowWithBg (model.go) both read the result back live,
// so nothing needs to be "baked into" calendar.org for either the
// tag-based-linking machinery or the calendar view's own display to stay
// correct across a resync.
package ui

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/sburnett/orgtd/internal/org"
)

// isMeetingTagsRecord reports whether h is itself a meeting-tags.org
// record (carries either kind's meetingTagsIDsProperty) rather than an
// ordinary outline entry — see entriesForMeeting's use of this, which
// keeps such a record from tag-matching its own meeting: it necessarily
// carries whatever tag it records, so without this check it would always
// show up as a "linked item" of the very meeting it's bookkeeping for.
func isMeetingTagsRecord(h *org.Headline) bool {
	return h.Properties[oneOffMeeting.meetingTagsIDsProperty()] != "" || h.Properties[recurringMeeting.meetingTagsIDsProperty()] != ""
}

// meetingTagsHeadlineFor returns tagsFile's headline recording tags for
// the meeting kind/id identifies (see meetingIdentity), or nil if none
// exists yet. Uses org.Walk rather than a flat scan of tagsFile.Headlines
// so a user who's manually reorganized entries in meetingTagsView (e.g.
// nested one under another for their own bookkeeping) doesn't break
// lookups.
func meetingTagsHeadlineFor(tagsFile *org.File, kind meetingIDKind, id string) *org.Headline {
	if tagsFile == nil {
		return nil
	}
	prop := kind.meetingTagsIDsProperty()
	var found *org.Headline
	org.Walk(tagsFile.Headlines, func(h *org.Headline) {
		if found != nil {
			return
		}
		for _, candidateID := range strings.Fields(h.Properties[prop]) {
			if candidateID == id {
				found = h
				return
			}
		}
	})
	return found
}

// meetingTagOverlay returns the tags meeting-tags.org durably records for
// the meeting kind/id identifies — nil if the file isn't loaded yet or
// has no matching entry. Two callers union this in: meetingTags
// (agenda.go), which feeds every tag-based-linking consumer (the
// agenda's Meetings section, :calendar's nested linked items, the
// gutter's meeting marker, the info buffer's "Meeting:" section, and the
// "gM" picker's filter-by-tag), and renderCalendarItemRowWithBg
// (model.go), which shows it directly on the meeting's own row. Both
// compute this live on every call rather than caching it, so a "gt" edit
// here — or a hand-edit made in meetingTagsView — takes effect
// immediately everywhere, with nothing to invalidate.
func (m *Model) meetingTagOverlay(kind meetingIDKind, id string) []string {
	h := meetingTagsHeadlineFor(m.findMeetingTagsFile(), kind, id)
	if h == nil {
		return nil
	}
	return h.Tags
}

// calendarDisplayTags returns the tags renderCalendarItemRowWithBg
// should show on a calendar event's own row: h's own tags (recurring,
// attendee) followed by any meeting-tags.org tags for it that aren't
// already present — purely a rendering-time union (see meetingTagOverlay
// above), so it never mutates h.Tags itself. h is assumed to be a synced
// calendar event; a no-op union (just h.Tags) if it somehow isn't.
func (m *Model) calendarDisplayTags(h *org.Headline) []string {
	kind, id, ok := meetingIdentity(h)
	if !ok {
		return h.Tags
	}
	overlay := m.meetingTagOverlay(kind, id)
	if len(overlay) == 0 {
		return h.Tags
	}
	tags := append([]string(nil), h.Tags...)
	for _, t := range overlay {
		if indexOfString(tags, t) < 0 {
			tags = append(tags, t)
		}
	}
	return tags
}

// indexOfHeadline returns the index of h within list, or -1 if it isn't
// there — used by applyMeetingTag to locate an existing meeting-tags.org
// entry's position for a deleteAction, the same way callers elsewhere in
// this package locate a headline's index before building a spliceAction.
func indexOfHeadline(list []*org.Headline, h *org.Headline) int {
	for i, cand := range list {
		if cand == h {
			return i
		}
	}
	return -1
}

// applyMeetingTag is "gt" on a calendarView entry (see applyTagInput):
// rather than editing the calendar event's own headline, which
// :sync-calendar would wipe out on its next wholesale regeneration, it
// records tag durably in meeting-tags.org instead — toggling it on
// whichever entry already records tags for this meeting (kind/id — see
// meetingIdentity), or creating a new one, seeded with target's own
// title for context, if none exists yet. Every branch below is exactly
// one pushUndo call touching only meeting-tags.org, so this is a single
// undo step, same as any other "gt" edit — calendar.org's live headline
// is never touched.
func (m *Model) applyMeetingTag(target *org.Headline, kind meetingIDKind, id, tag string) {
	if tag == meetingSeriesTag {
		m.message = `"recurring" is reserved and can't be used as a meeting tag`
		return
	}

	tagsFile := m.findMeetingTagsFile()
	if tagsFile == nil {
		// Nothing has ever been tagged via "gt" before — materialize the
		// file's workspace entry lazily, mirroring exactly how
		// finishSyncCalendar (sync_calendar.go) does the same for the
		// calendar file the first time :sync-calendar runs.
		tagsFile = &org.File{Path: filepath.Join(m.ws.Dir, m.meetingTagsFile)}
		m.ws.Files = append(m.ws.Files, tagsFile)
		sort.Slice(m.ws.Files, func(i, j int) bool { return m.ws.Files[i].Path < m.ws.Files[j].Path })
	}

	existing := meetingTagsHeadlineFor(tagsFile, kind, id)
	if existing == nil {
		h := &org.Headline{Level: 1, Title: target.Title, Tags: []string{tag}}
		h.SetProperty(kind.meetingTagsIDsProperty(), id)
		m.pushUndo(&insertAction{spliceAction{f: tagsFile, index: len(tagsFile.Headlines), headlines: []*org.Headline{h}}})
		return
	}

	old := append([]string(nil), existing.Tags...)
	var newTags []string
	removed := false
	for _, t := range existing.Tags {
		if t == tag {
			removed = true
			continue
		}
		newTags = append(newTags, t)
	}
	if !removed {
		newTags = append(newTags, tag)
	}
	if removed && len(newTags) == 0 {
		// The last tag on this entry was just removed — nothing left to
		// record, so prune the whole headline rather than leaving a
		// meaningless tagless stub behind.
		parent := existing.Parent
		list := tagsFile.Headlines
		if parent != nil {
			list = parent.Children
		}
		index := indexOfHeadline(list, existing)
		m.pushUndo(&deleteAction{spliceAction{f: tagsFile, parent: parent, index: index, headlines: []*org.Headline{existing}, inTree: true}})
		return
	}
	m.pushUndo(&tagChangeAction{h: existing, f: tagsFile, oldTags: old, newTags: newTags})
}

// meetingTagsMatchingEvents returns every currently-synced calendar
// event (across the whole workspace, any file) whose identity
// (meetingIdentity) matches one of h's own MEETING_TAG_RECURRING_EVENT_IDS/
// MEETING_TAG_EVENT_IDS IDs — nil if h isn't a meeting-tags.org record at
// all (isMeetingTagsRecord), or none of its IDs currently resolve to a
// synced occurrence. That second case is meeting-tags.org's own window
// into a stale record: an ID whose series was deleted and recreated (a
// new GCAL_RECURRING_EVENT_ID), or a one-off event that's aged out of
// the sync window, simply shows nothing nested under it in
// meetingTagsView, rather than silently doing nothing forever. Sorted
// chronologically by start time, like :calendar's own day-by-day
// ordering.
func (m *Model) meetingTagsMatchingEvents(h *org.Headline) []*org.Headline {
	recurIDs := strings.Fields(h.Properties[recurringMeeting.meetingTagsIDsProperty()])
	eventIDs := strings.Fields(h.Properties[oneOffMeeting.meetingTagsIDsProperty()])
	if len(recurIDs) == 0 && len(eventIDs) == 0 {
		return nil
	}
	var matches []*org.Headline
	for _, f := range m.ws.Files {
		org.Walk(f.Headlines, func(cand *org.Headline) {
			kind, id, ok := meetingIdentity(cand)
			if !ok {
				return
			}
			ids := eventIDs
			if kind == recurringMeeting {
				ids = recurIDs
			}
			if indexOfString(ids, id) >= 0 {
				matches = append(matches, cand)
			}
		})
	}
	sort.SliceStable(matches, func(i, j int) bool {
		si, _ := parseRFC3339Property(matches[i], "GCAL_START")
		sj, _ := parseRFC3339Property(matches[j], "GCAL_START")
		return si.Before(sj)
	})
	return matches
}

// appendMeetingTagsHeadlines is appendHeadlines' meetingTagsView
// counterpart (see appendMeetingTagsRows, model.go): same recursion
// (body lines, children), but a headline that's itself a
// meeting-tags.org record (isMeetingTagsRecord) is marked
// isMeetingTagsRecordRow (see renderMeetingTagsRecordRowWithBg — a
// tighter row than the default headline case, no indent/fold columns),
// and has every calendar event it currently matches
// (meetingTagsMatchingEvents) appended right after it, one level
// deeper — the meeting-tags.org analogue of appendCalendarHeadlines
// nesting linked items under each event, so browsing :meeting-tags shows
// at a glance which synced occurrences a record's IDs actually resolve
// to right now. Genuinely one level deeper (not flush with the record),
// and not just visually: row.level is also what moveDeeper/
// moveShallower (see model.go) use to decide what "l"/"h" step into or
// out of, so a nested event's level is what makes it reachable as the
// record's "child" via those keys, the same way
// renderCalendarLinkedItemRowWithBg's r.level-based indent does for
// :calendar's own linked items (its actual rendered indent is separately
// capped — see renderCalendarItemRowWithBg). Each nested event row is
// marked isCalendarItem, the same as its own row in :calendar (same
// headline pointer), so it renders, folds, and edits identically —
// including "gt", which applyTagInput routes right back to this same
// record.
func (m *Model) appendMeetingTagsHeadlines(dst *[]row, headlines []*org.Headline, ignoreFold bool) {
	for _, h := range headlines {
		if m.hiddenAsStaleDone(h) {
			continue
		}
		*dst = append(*dst, row{headline: h, level: h.Level, isMeetingTagsRecordRow: isMeetingTagsRecord(h)})
		if ignoreFold || !m.collapsed[h] {
			m.appendBodyLines(dst, h)
			if len(h.Children) > 0 {
				m.appendMeetingTagsHeadlines(dst, h.Children, ignoreFold)
			}
		}
		for _, event := range m.meetingTagsMatchingEvents(h) {
			if _, ok := m.collapsed[event]; !ok {
				m.collapsed[event] = true
			}
			*dst = append(*dst, row{headline: event, level: h.Level + 1, isCalendarItem: true})
			if ignoreFold || !m.collapsed[event] {
				m.appendBodyLines(dst, event)
			}
		}
	}
}
